from fastapi import APIRouter
from app.api.v1 import auth, scans, users, tenants, findings, billing, websocket, remediation, enforcement, evidence, metrics





































































































































































































































































































































































-- End of Phase 7 Documentation5. **Non-predatory** - Security should be accessible, enforcement should be earned4. **Inclusive** - Free users get real enforcement, just rate-limited3. **Transparent** - Every decision is queryable and auditable2. **No overrides** - If it blocks, something must be fixed1. **Enforcement is deterministic** - Same math, same rules, every time-------------Key Takeaways```}    }        }            }                error("Deployment blocked by ForgeScan")            if (decision == "BLOCK") {            def decision = readJSON(text: response).decision            ).trim()                returnStdout: true                    "https://api.forgescan.io/api/v1/enforce/gate?tenant_id=$TENANT_ID"''',                script: '''curl -s -H "Authorization: Bearer $FORGESCAN_TOKEN" \\            def response = sh(        script {    steps {stage('ForgeScan Gate') {```groovy**Jenkins:**```    - if echo $RESULT | jq -e '.decision == "BLOCK"' > /dev/null; then exit 1; fi    - RESULT=$(curl -s -H "PRIVATE-TOKEN: $FORGESCAN_TOKEN" "https://api.forgescan.io/api/v1/enforce/gate?tenant_id=$TENANT_ID")  script:  stage: pre-deployforgescan_gate:```yaml**GitLab CI:**```      jq -e '.decision == "BLOCK"' && exit 1 || exit 0      "https://api.forgescan.io/api/v1/enforce/gate?tenant_id=$TENANT_ID" | \    curl -s -H "Authorization: Bearer $FORGESCAN_TOKEN" \  run: |- name: ForgeScan Gate```yaml**GitHub Actions:**### CI Integration Examples```pytest backend/tests/test_enforcement.py -v# Run testspsql -U postgres -d forgescan < backend/security/phase7_enforcement_rules.sql# Load Phase 7 SQL```bash### Local Testing--------------------Testing & DeploymentNo escape hatch. No override. No committee.- Enforcement: Phase 7 (CI/CD gates)- Prioritization: Phases 3–5 (DPL engine)- Detection: Phase 2 (parsers)Phase 7 enforces the deterministic decisions produced by Phases 2–5.------------------------Phase 7 Outcome (Locked)```);    soft_fails_allowed BOOLEAN DEFAULT TRUE    hard_fails_used INTEGER DEFAULT 0,    hard_fails_limit INTEGER,      -- NULL = unlimited    quota_year_month TEXT,         -- YYYY-MM    tenant_id UUID NOT NULL UNIQUE,    quota_id UUID PRIMARY KEY,CREATE TABLE forgescan_security.enforcement_quota (```sql### enforcement_quota (Tier-Based Rate Limiting)```);    acked_at TIMESTAMPTZ    acked_by UUID,    decided_at TIMESTAMPTZ DEFAULT NOW(),    required_action TEXT,    financial_risk_usd DECIMAL(15, 2),    asset_at_risk TEXT,    reason TEXT,    decision TEXT NOT NULL,    enforcement_level TEXT,    max_priority INTEGER,    pipeline_id TEXT,    tenant_id UUID NOT NULL,    decision_id UUID PRIMARY KEY,CREATE TABLE forgescan_security.enforcement_decisions (```sql### enforcement_decisions (Immutable Audit Trail)---------------Database SchemaOn-call engineer can look up why their build was blocked.```}  ...  "decision": "BLOCK",  "enforcement_level": "HARD_FAIL",  "max_priority": 120,  "pipeline_id": "jenkins-build-123",  "tenant_id": "550e8400-e29b-41d4-a716-446655440000",  "decision_id": "550e8400-e29b-41d4-a716-446655440001",{Response:GET /api/v1/enforce/decision/{decision_id}```### 5. Decision LookupIf "allowed": false, tier needs upgrade.```}  "tier": "STARTUP"  "reason": "Quota check passed.",  "allowed": true,  "tenant_id": "550e8400-e29b-41d4-a716-446655440000",{Response:GET /api/v1/enforce/quota?tenant_id={uuid}```### 4. Quota CheckEvery enforcement decision is queryable and reproducible.```}  "count": 1  ],    }      "decided_at": "2025-12-21T10:30:00Z"      "financial_risk_usd": 50000,      "asset_at_risk": "public.orders",      "reason": "...",      "decision": "BLOCK",      "enforcement_level": "HARD_FAIL",      "max_priority": 120,      "pipeline_id": "jenkins-build-123",      "decision_id": "...",    {  "decisions": [  "tenant_id": "550e8400-e29b-41d4-a716-446655440000",{Response:GET /api/v1/enforce/history?tenant_id={uuid}&limit=100```### 3. Enforcement History (Audit Trail)Used when enforcing a SOFT_FAIL (80-99 priority) that requires human approval before deploy.```}  "decision_id": "550e8400-e29b-41d4-a716-446655440001"  "message": "Decision acknowledged by user@example.com",  "success": true,{Response:}  "decision_id": "550e8400-e29b-41d4-a716-446655440001"{Request:POST /api/v1/enforce/acknowledge```### 2. Soft Fail Acknowledgement```}  "decision_id": "550e8400-e29b-41d4-a716-446655440000"  "reason": "...",  "enforcement_level": "HARD_FAIL|SOFT_FAIL|WARN|INFO",  "max_priority": 120,  "decision": "BLOCK|ALLOW_WITH_ACK|ALLOW|INFO",{Response:GET /api/v1/enforce/gate?tenant_id={uuid}&pipeline_id={id}```### 1. Main Gate Decision-------------API Endpoints"Security should be accessible — enforcement should be earned."This aligns with:- Limit historical retention (free: 30 days, startup+: 1 year)- Limit CI/CD automation depth (free: soft gate only)- Limit enforcement velocity (free: 1 hard fail/month)You DO:- Artificially downgrade security- Reduce scan quality- Hide vulnerabilitiesYou do NOT:--------------------------------------------Monetization Locks (Without Being Predatory)No black boxes. No ML explanations. No hand-waving.- Phase 6 business tier- Phase 5 deterministic rules- Phase 4 audit logsThis ties directly back to:```}  "required_action": "ALTER TABLE tenant1.orders FORCE ROW LEVEL SECURITY"  "financial_risk_usd": 50000,  "asset_at_risk": "tenant1.orders",  "reason": "Critical business risk detected (revenue/compliance impact)",  "enforcement_level": "HARD_FAIL",  "max_priority": 120,  "decision": "BLOCK",{```jsonEvery block produces:---------------------------------------------Enforcement Transparency (Why Users Trust It)Free users still get real enforcement, just rate-limited, not crippled.**Key idea:**| Enterprise | Unlimited | Custom | Full || Growth | Unlimited | Full gate + SLA | Full || Startup | Unlimited | Full gate | Full || Free | 1/month | Soft gate | Limited ||---|---:|---|---|| Tier | Max Hard Blocks | CI/CD Gate | Business Context |Tier Enforcement Matrix:So enforcement scales by tier, not by feature removal.--------------------------------------------Tier-Based Enforcement (Inclusive by Design)This is the monetization choke point.```    fi      exit 1      echo "❌ Deployment blocked by ForgeScan"    if [ "$DECISION" = "BLOCK" ]; then        echo "ForgeScan Decision: $DECISION (Priority: $PRIORITY)"        PRIORITY=$(echo $RESPONSE | jq -r '.max_priority')    DECISION=$(echo $RESPONSE | jq -r '.decision')          https://api.forgescan.io/api/v1/enforce/gate?tenant_id=$TENANT_ID&pipeline_id=$GITHUB_RUN_ID)    RESPONSE=$(curl -s -H "Authorization: Bearer $FORGESCAN_TOKEN" \  run: |- name: ForgeScan Release Gate```yamlExample: GitHub Actions----------------------------------------------CI/CD Integration Flow (How Customers Use It)- ForgeScan remains the source of truth- They only consume the decision- CI tools do not calculate risk**Important:**```$$;...SECURITY DEFINER STABLE AS $$LANGUAGE plpgsql)    reason TEXT    enforcement_level TEXT,    max_priority INTEGER,    decision TEXT,RETURNS TABLE ()    p_pipeline_id TEXT    p_tenant_id UUID,CREATE OR REPLACE FUNCTION forgescan_security.enforce_release_gate(```sql3.1 Enforcement Function (Database-Level Truth)-----------------------------------CI/CD Gate Engine (Core of Phase 7)This is not configurable per scan — only per tenant tier.| < 60 | INFO | No enforcement || 60–79 | WARN | Logged, visible in dashboard || 80–99 | SOFT_FAIL | Allow deploy, require acknowledgement || ≥ 100 | HARD_FAIL | Block CI/CD, block deployment ||---|---|---|| Priority Score | Enforcement Level | Behavior |Enforcement Bands (Hard Rules):We introduce Enforcement Levels derived from the final priority score produced in Phase 5.--------------------------------Deterministic Enforcement LevelsNo AI. No opinions. Only deterministic, auditable decisions.Security findings only matter if they can stop bad business outcomes.**Key principle:**- You enforce**Phase 7 adds:**- You explain business impact- You prioritize- You detect**Up to Phase 6:**-------------------------------------------Enforcement Philosophy (Why Phase 7 Exists)This is where ForgeScan becomes operationally unavoidable.- Create clear value boundaries between free, startup, and paid plans- Enforce tier limits fairly- Block bad releasesTurn findings + business context into non-negotiable enforcement points that:---------------Goal of Phase 7Date: 2025-12-21
api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(scans.router, prefix="/scans", tags=["scans"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(tenants.router, prefix="/tenants", tags=["tenants"])
api_router.include_router(findings.router, prefix="/findings", tags=["findings"])
api_router.include_router(billing.router, prefix="/billing", tags=["billing"])
api_router.include_router(remediation.router, tags=["remediation"])
api_router.include_router(enforcement.router, tags=["enforcement"])
api_router.include_router(evidence.router, tags=["evidence"])
api_router.include_router(metrics.router, tags=["metrics"])